### ISSUE TITLE
Exploration in PPO

### ISSUE THREAD

**Issue by zishanahmed08** [openai/baselines#280]
This is more of a question than an issue.How do I influence the exploration in PPO?

I am trying to integrate PPO algorithm to teach the turtlebot avoid abstacles with gym-gazebo [More details here](https://github.com/erlerobot/gym-gazebo/blob/master/imgs/GazeboCircuit2TurtlebotLidar-v0.png)

At present i face the issue that my turtle bot keeps revolving(looping)in circles:I have introduced huge negative rewards to discourage this behavior. But it does not help.Next, I terminated the episode when looping is detected.But the same looping behavior persists in the next episodes.
How do I solve this? Below are some ideas

1. Increase the value of **entropy coeff** to encourage exploration

2. The action space of the turtlebot is 5 discrete action actions (hard left.left,straight,right,hard right).Could it be that the probably the  probabilities are skewed towards left(it loops in anti-clockwise) and it would be better to have a continuous action space?

Your suggestions would be appreciated.

PS-With DDQN, the turtlebot learns to avoid obstacles in 1.6 million steps(1 million exploration steps included).How many steps should i expect before the turtle bot solves it with PPO?

**Comment by olegklimov** [comment]
Hi @zishanahmed08 . Exploration in general is hard. In some cases, you can make exploration work in PPO by giving out reward, for example for visiting states less visited historically. The limitations here:
1. Your state may have a lot of dimensions, so you can't define 'state visited' good enough.
2. Exploration implemented like this changes your policy all the time.

Entropy coef has little real world effect on learning, despite good theoretical foundation.

You can expect well-tuned PPO to work equally well as tuned DDPG on continuous control. DDPG is off-policy, but that's important only if you have demonstrations as an input, otherwise they both progress on-policy.

Also watch out for simple failure modes, like reward scaling (or advantage normalizing) amplifying very small noise in reward or value estimation, that will make policy to commit to wrong solutions very fast.

**Comment by zishanahmed08** [comment]
HI @olegklimov -Thanks for your suggestions..What are you thoughts on my 2nd question

2. The action space of the turtlebot is 5 discrete action actions (hard left.left,straight,right,hard right).Could it be that the probably the probabilities are skewed towards left(it loops in anti-clockwise) and it would be better to have a continuous action space?

**Comment by olegklimov** [comment]
left: no, that's not possible if you run learning many times.

continuous is better: about the same, doesn't change the complexity of the task. Discrete actions may be better for exploration (i.e. to find the reward for the first time)
