### ISSUE TITLE
TypeError: Can't instantiate abstract class SubprocVecEnv with abstract methods step_async, step_wait

### ISSUE THREAD

**Issue by okdolly** [openai/baselines#373]
In this line, ```env = SubprocVecEnv(FLAGS.num_agents + FLAGS.num_scripts, FLAGS.map)```

I experienced:
```
Traceback (most recent call last):
  File "train_mineral_shards.py", line 305, in <module>
    main()
  File "train_mineral_shards.py", line 171, in main
    env = SubprocVecEnv(FLAGS.num_agents + FLAGS.num_scripts, FLAGS.map)
TypeError: Can't instantiate abstract class SubprocVecEnv with abstract methods step_async, step_wait
```
Here's the code block
```
 elif (FLAGS.algorithm == "a2c"):

    num_timesteps = int(40e6)

    num_timesteps //= 4

    seed = 0

    env = SubprocVecEnv(FLAGS.num_agents + FLAGS.num_scripts, FLAGS.map)

    policy_fn = CnnPolicy
    a2c.learn(
      policy_fn,
      env,
      seed,
      total_timesteps=num_timesteps,
      nprocs=FLAGS.num_agents + FLAGS.num_scripts,
      nscripts=FLAGS.num_scripts,
      ent_coef=0.5,
      nsteps=FLAGS.nsteps,
      max_grad_norm=0.01,
      callback=a2c_callback)

```

Source: line 168 in (https://github.com/chris-chris/pysc2-examples/blob/master/train_mineral_shards.py)

**Comment by araffin** [comment]
SubprocVecEnv requires a list of environments as argument: https://github.com/openai/baselines/blob/master/baselines/common/vec_env/subproc_vec_env.py#L32
you can look at an example here: https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/master/main.py#L61

**Comment by Kelvinson** [comment]
As far I can see,  in the definition of SubprocVecEnv, the init function is  https://github.com/chris-chris/pysc2-examples/blob/f89604c1c68c5bcab29ae1eddb9e5fa5ada3b917/common/vec_env/subproc_vec_env.py#L137
__init__(self, nenvs, nscripts, map_name):
so you can try with 
env = SubprocVecEnv(FLAGS.num_agents,  FLAGS.num_scripts, FLAGS.map)

**Comment by unixpickle** [comment]
This was an issue with [chris-chris/pysc2-examples](https://github.com/chris-chris/pysc2-examples), not with baselines. It looks like the bug was fixed 13 days ago in [this commit](https://github.com/chris-chris/pysc2-examples/commit/92f3ebb0c1222fe1052b94b80d0a90c43c7b8116).

As a backstory, we changed how the `VecEnv` class works, and changed `SubprocVecEnv` accordingly; our version of `SubprocVecEnv` works just fine. This broke [chris-chris/pysc2-examples](https://github.com/chris-chris/pysc2-examples) because it contained an old, copied and pasted version of `SubprocVecEnv`.
