### ISSUE TITLE
Support for Fetch environments?

### ISSUE THREAD

**Issue by jeremyf21** [openai/baselines#380]
It seems like baselines is not directly implemented to deal with `Box()` type action spaces.  This same exact code works for the `CartPole` environment.  It fails on `FetchReach-v1`.  Here is the code:

```
import gym
from baselines import deepq


def callback(lcl, _glb):
    # stop training if reward exceeds 199
    is_solved = lcl['t'] > 100 and sum(lcl['episode_rewards'][-101:-1]) / 100 >= 199
    return is_solved


def main():
    env = gym.make("FetchReach-v1")
    model = deepq.models.mlp([64])
    act = deepq.learn(
        env,
        q_func=model,
        lr=1e-3,
        max_timesteps=100000,
        buffer_size=50000,
        exploration_fraction=0.1,
        exploration_final_eps=0.02,
        print_freq=10,
        callback=callback
    )
    print("Saving model to Fetch_model.pkl")
    act.save("Fetch_model.pkl")


if __name__ == '__main__':
    main()
```

When I try to use the same `deepq` algorithm trained on `cartpole`, with a discrete action space, on `FetchReach-V1`, I get the following:
```
File "train_FetchReach.py", line 31, in <module>
    main()
  File "train_FetchReach.py", line 24, in main
    callback=callback
  File "/home/jeremy/.local/share/virtualenvs/cgw-i4TbRcn4/lib/python3.6/site-packages/baselines/deepq/simple.py", line 180, in learn
    num_actions=env.action_space.n,
AttributeError: 'Box' object has no attribute 'n'
```

I tried adding

`env.action_space.n = len(env.action_space.sample())`

but that just lead to more errors:

```
Traceback (most recent call last):
  File "train_FetchReach.py", line 32, in <module>
    main()
  File "train_FetchReach.py", line 25, in main
    callback=callback
  File "/home/jeremy/.local/share/virtualenvs/cgw-i4TbRcn4/lib/python3.6/site-packages/baselines/deepq/simple.py", line 184, in learn
    param_noise=param_noise
  File "/home/jeremy/.local/share/virtualenvs/cgw-i4TbRcn4/lib/python3.6/site-packages/baselines/deepq/build_graph.py", line 376, in build_train
    act_f = build_act(make_obs_ph, q_func, num_actions, scope=scope, reuse=reuse)
  File "/home/jeremy/.local/share/virtualenvs/cgw-i4TbRcn4/lib/python3.6/site-packages/baselines/deepq/build_graph.py", line 177, in build_act
    observations_ph = make_obs_ph("observation")
  File "/home/jeremy/.local/share/virtualenvs/cgw-i4TbRcn4/lib/python3.6/site-packages/baselines/deepq/simple.py", line 175, in make_obs_ph
    return BatchInput(observation_space_shape, name=name)
  File "/home/jeremy/.local/share/virtualenvs/cgw-i4TbRcn4/lib/python3.6/site-packages/baselines/deepq/utils.py", line 66, in __init__
    super().__init__(tf.placeholder(dtype, [None] + list(shape), name=name))
TypeError: 'NoneType' object is not iterable
```

**Comment by pzhokhov** [comment]
as @elifriedman pointed out, DQN is build to handle discrete action spaces with finite (and not too large) number of actions. See discussion here: https://stackoverflow.com/questions/7098625/generalizing-q-learning-to-work-with-a-continuous-action-space?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
The gist of the problem is the following - action selection in Q-learning involves evaluating Q function over all possible actions and choosing the action with largest Q value, which is not possible for continuous action spaces. This problem can be tackled by using policy gradient methods in which the policy outputa the action directly (see e.g. this paper https://arxiv.org/pdf/1509.02971.pdf). 
In terms of practical advice - baselines offer multiple policy gradient methods that can be applied to continuous action spaces (A2C, PPO, TRPO). For an example of using PPO with continuous action spaces, see here: https://github.com/openai/baselines/blob/master/baselines/ppo2/run_mujoco.py

**Comment by jeremyf21** [comment]
@pzhokhov thanks,

I have some basic questions. I am currently implementing my own environment.  I have it such that the observation space is a 1xN vector, and the action space is a Discrete space (just like cartpole).

Is it possible and even worthwhile to adapt this code to be used by `A2C`? If so, what are the steps I need to take?  Is it simply a question of reshaping my observation space?

Currently, when running my own custom `env` (which has been succesfully run on `deepq`), I get the following:

  File "run_atari.py", line 33, in <module>
    main()
  File "run_atari.py", line 30, in main
    policy='lstm', lrschedule=args.lrschedule, num_env=16)
  File "run_atari.py", line 19, in train
    learn(policy_fn, env, seed, total_timesteps=int(num_timesteps * 1.1), lrschedule=lrschedule)
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/a2c/a2c.py", line 140, in learn
    max_grad_norm=max_grad_norm, lr=lr, alpha=alpha, epsilon=epsilon, total_timesteps=total_timesteps, lrschedule=lrschedule)
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/a2c/a2c.py", line 30, in __init__
    step_model = policy(sess, ob_space, ac_space, nenvs, 1, reuse=False)
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/ppo2/policies.py", line 64, in __init__
    h = nature_cnn(X)
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/ppo2/policies.py", line 14, in nature_cnn
    **conv_kwargs))
  File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/a2c/utils.py", line 54, in conv
    nin = x.get_shape()[channel_ax].value
  File "/home/jeremy/.local/share/virtualenvs/algorithms-YDeT6CT5/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 521, in __getitem__
    return self._dims[key]
IndexError: list index out of range

**Comment by nicklafarge** [comment]
@jeremyf21 I am having the same problem. Did you ever figure this out?

**Comment by andytwigg** [comment]
This is because your observation space doesn't have a channel dimension.
Try running with --policy mlp

**Comment by pzhokhov** [comment]
@jeremyf21 , as @andytwigg pointed out, run_atari.py assumes that observations are stacks of atari frames, and tries to deal with them as with images, by applying 2d convolutional layers first (that's what 
```
File "/home/jeremy/catkin_ws/src/algorithms/baselines/baselines/ppo2/policies.py", line 64, in __init__
    h = nature_cnn(X)
```
frame of the stacktrace does). If in your case observations are 1xNs vectors, the fully connected (mlp) policy would be more appropriate.
Unfortunately, there is a bug in master branch at the moment where a2c converts observations to uint8 type, so in many cases a2c won't work even with fully connected policy (and the worst part is that it won't crash, it just will sliently not work. 
Specifically, this line: https://github.com/openai/baselines/blob/f2729693253c0ef4d4086231d36e0a4307ec1cb3/baselines/a2c/a2c.py#L110

The fix is in a PR along with a bunch of refactoring: https://github.com/openai/baselines/pull/490
For the examples of using A2C with Cartpole (which is essentially the use case you are describing), see this test: 
https://github.com/openai/baselines/blob/peterz_migrate_rlalgs/baselines/common/tests/test_cartpole.py

**Comment by nicklafarge** [comment]
Thank you so much for the help. I think this has me pointed in the right direction. (Or at least resolved the error I'm having for now)

**Comment by carlo-** [comment]
The robotics environments are not compatible with baselines out of the box (except maybe with HER), because they have a dictionary-based observation space. To use them, you have to flatten the observation space into an array like so:

```python
env = gym.wrappers.FlattenDictWrapper(env, dict_keys=[′observation′, ′desired_goal′])
```

This worked for me perfectly with DDPG and FetchPickAndPlace.

More info on this at the bottom of [this page](https://blog.openai.com/ingredients-for-robotics-research/#content).

**Comment by WuXinyang2012** [comment]
@carlo- Hi, I am facing the same problem now. 
I am trying to use DDPG in the FetchReach-v1 environment:
```bash
python -m baselines.run --alg=ddpg --env=FetchReach-v1 --num_timesteps=1e6
```
it tells me:
```bash
TypeError: can only concatenate tuple (not "NoneType") to tuple
```

I believe that the problem is exactly what u said, the robotics envs have a dictionary-based observation space. But I do not know where to use your code, this FlattenDictWrapper. I put it in the line 73 in the run.py, but it returns some other new errors now. 

Can u please tell me in which file or in which line you used this wrapper to flatten the observation space?

Thanks in advance!

**Comment by pzhokhov** [comment]
@WuXinyang2012 I made a hacky commit in which FlattenDictWrapper is applied in common/cmd_util.py::make_env, here: https://github.com/openai/baselines/commit/28b056732c182c31685a6a9b873e712021210b2e (the command that you provided works for me in that commit)

**Comment by pzhokhov** [comment]
more principled solution is currently in the works

**Comment by carlo-** [comment]
@WuXinyang2012 it should go anywhere before calling train(). I actually ended up switching to stable-baselines for this and similar issues. I hope it helps!
