### ISSUE TITLE
A2C saving and loading issues

### ISSUE THREAD

**Issue by njustesen** [openai/baselines#390]
I was unable to save my model with the save function in the Model class. I had to change it to:

> def save(path, model_name):
>     ps = sess.run(params)
>     make_path(path)
>     joblib.dump(ps, path + model_name)

However, when I try to load the model, I get this error:

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 1 and 4 for 'Assign_1' (op: 'Assign') with input shapes: [32], [1,32,1,1].

Are ther some example code that saves and loads a model?

**Comment by pzhokhov** [comment]
I suspect tensorflow sessions don't play nicely with joblib.dumps serialization for some reason. 
Could you provide more info on how were you trying to save and load the model? 
Alternatively, the routines for saving / loading the default tensorflow session can be found here: 
https://github.com/openai/baselines/blob/69f25c6028d71e23a7b267b0e1071ad216290f91/baselines/deepq/utils.py#L9
(this code will soon migrate into common.tf_utils)

**Comment by pzhokhov** [comment]
my bad, I think this is still a problem

**Comment by pzhokhov** [comment]
At a closer look, the save/load methods in A2C and PPO2 don't have a bug per se, but can be sensitive to the way the model is loaded. 
For instance, the following snippet works (and loads trained model) in the master branch:
(assuming save_path is a non-existing path to the file where the model will be saved)

```
with tf.Graph().as_default(), tf.Session().as_default():
            # train and save the model
            model = a2c.learn(policy=MlpPolicy, env=env, total_timesteps=50000, seed=0)
            model.save(model_path)
 
with tf.Graph().as_default(), tf.Session().as_default():
           # load the model - train the model for zero steps and then load the parameters
           model = a2c.learn(policy=MlpPolicy, env=env, total_timesteps=0, seed=0)
           model.load(model_path)
```
Ideally though is to have more serialization (pickle, json)-like API, in which, for instance, `a2c.load(path)` returns the trained model. I'll mark this is as an enhancement instead of a bug, and we'll work on this as part of the trainer <-> policy api.

**Comment by DanielTakeshi** [comment]
@pzhokhov Just to be clear, it seems like there's two ways to save the model: using the `model.save` and the tensorflow saver that deepq uses? And similarly for loading? Which one is the recommended way with A2C?

**Comment by pzhokhov** [comment]
@DanielTakeshi the model.save and model.load are actually rather similar (at least in usage) to tensorflow saver used by deepq load_state and save_state - both save / restore the tf variables in the current tf session; both require re-initialization of the model when loading; both allow to continue training. Which one these to use is largely a matter or convenience / preference (at least at the moment).

**Comment by saddy001** [comment]
Model.save in a2c.py:
```
def save(save_path):
    ps = sess.run(params)
    make_path(save_path)
    joblib.dump(ps, save_path)
```
raises IsADirectoryError, because indeed, save_path is a directory.

**Comment by saddy001** [comment]
Instead, I guess it should be something like this
```
def save(save_file):
    ps = sess.run(params)
    path = os.path.dirname(os.path.abspath(save_file))
    
    if not os.path.exists(path):
        make_path(save_path)
        
    joblib.dump(ps, save_file)
```

**Comment by saddy001** [comment]
And a2c.learn should return the model, instead of None.

**Comment by saddy001** [comment]
Oh, I see. The pip version is outdated.

**Comment by pzhokhov** [comment]
@saddy001 correct, the version in pypi is rather outdated. Please use the github instead. 
We would like baselines to be less of a library, and more of a collection of algorithms for people (and AIs :)) to play with, so there was an decision to stop releasing the pypi package. 
The fix for original problem went in with the recent refactor PR; so I am closing this issue.
