### ISSUE TITLE
Fix bug in Deepq module import error

### ISSUE THREAD

**Issue by fstonezst** [openai/baselines#394]
There is a module import bug in the deepq.sample.
from baselines import deepq should be modify to from baselines.deepq import build_graph
the function build_act is write in the build_graph not in the init file.

@pzhokhov Thanks for noticing my issue. But this bug still exists. I fixed it in PR (#352), or you can fix it by yourself. : )

 
==================================
$ python /baselines/baselines/deepq/experiments/train_cartpole.py

Traceback (most recent call last):
File "train_cartpole.py", line 3, in 
from baselines import deepq
File "/home/peter/Downloads/baselines/baselines/deepq/init.py", line 3, in 
from baselines.deepq.simple import learn, load # noqa
File "/home/peter/Downloads/baselines/baselines/deepq/simple.py", line 13, in 
from baselines import deepq
ImportError: cannot import name 'deepq'

**Comment by pzhokhov** [comment]
@fstonezst thank you for checking back on it so promptly! I still believe the issue is already fixed :) Note that in baselines/baselines/__init__.py we import build_train and build_act methods from build_graph submodule, here: https://github.com/openai/baselines/blob/9cf95a00542dc87b413e765d8c0fdcf0b1684cdc/baselines/deepq/__init__.py#L2
(this addresses the changes you are suggesting in the PR (https://github.com/openai/baselines/pull/352). I tried running
`python baselines/deepq/experiments/train_cartpole.py` with the latest version of baselines master installed, and it works. 
Please make sure you have pip installed the latest master (`git pull origin master && pip install -e .`), and then try again. If the error persists, let's talk more - I'll keep this issue open.

**Comment by fstonezst** [comment]
OK , I will close this issue since the code has passed your test.
Thank you for watching this issue!
