### ISSUE TITLE
AC2 Dones Population

### ISSUE THREAD

**Issue by sccrthlt** [openai/baselines#404]
Why are `dones` being appended to `mb_dones` so irregularly?  I have included comments below to reflect how I think they should be appended.

    class Runner(AbstractEnvRunner):

        def __init__(self, env, model, nsteps=5, gamma=0.99):
            super().__init__(env=env, model=model, nsteps=nsteps)
            ...

        def run(self):
            mb_obs, mb_rewards, mb_actions, mb_values, mb_dones = [],[],[],[],[]
            ...
            for n in range(self.nsteps):
                actions, values, states, _ = self.model.step(self.obs, self.states, self.dones)
                ...
                mb_dones.append(self.dones) # this line should not be here? ********************
                obs, rewards, dones, _ = self.env.step(actions)
                ...
                self.dones = dones
                # mb_dones.append(dones) should be here ***************************************
                for n, done in enumerate(dones):
                    if done:
                        self.obs[n] = self.obs[n]*0
                self.obs = obs
                ...
            mb_dones.append(self.dones) # this line should not be here? ************************

**Comment by opherlieber** [comment]
You can see a few lines later it actually 'shifts' and takes the dones correctly:
mb_dones = mb_dones[:, 1:]
So the final mb_dones is as you expect (the 'done' from the steps result and not 1 before)

It seems the code is build this way because the 'mb_masks' needs the dones from the previous step, so it saves +1 dones and takes the relevant ones for each mb_dones and mb_masks:
        mb_masks = mb_dones[:, :-1]
        mb_dones = mb_dones[:, 1:]

**Comment by sccrthlt** [comment]
@opherlieber makes sense.  Thank you for your explanation.
