### ISSUE TITLE
ppo2.py not updating act model policy from old policy   

### ISSUE THREAD

**Issue by agrib** [openai/baselines#467]
why there is no update policy from old policy for new round of data in update for loop of learn function

**Comment by brett-daley** [comment]
`act_model` and `train_model` share parameters because `reuse=True` in the second declaration:
https://github.com/openai/baselines/blob/f2729693253c0ef4d4086231d36e0a4307ec1cb3/baselines/ppo2/ppo2.py#L17-L18

So only `train_model` needs to be updated and `act_model` is automatically updated too. The update is conducted by calling this [function](https://github.com/openai/baselines/blob/f2729693253c0ef4d4086231d36e0a4307ec1cb3/baselines/ppo2/ppo2.py#L52-L63) in the for loop [here](https://github.com/openai/baselines/blob/f2729693253c0ef4d4086231d36e0a4307ec1cb3/baselines/ppo2/ppo2.py#L199).

**Comment by pzhokhov** [comment]
@brett-daley correct. Closing this.
