### ISSUE TITLE
Why does ppo2_mujoco only use a single process to a env? 

### ISSUE THREAD

**Issue by RebornHugo** [openai/baselines#479]
1. Why does ppo2_mujoco only use a single process to a env, whereas atari is using 8 envs?  I guess mujoco will take so much resource or it's hard to use multiple envs ?

2. What's the point that ppo2_atari's learning rate and clip_range are annealing, but in mujoco, they are fixed float numbers ?

**Comment by kirk86** [comment]
I don't really the answer to your question but could that be related to the fact that ppo2 is optimized for gpu and thus might not required multiple processes to run like for instance ppo1?

**Comment by pzhokhov** [comment]
1. Mujoco simluator is not that demanding computationally, actually; so one can run multiple envs in principle - I think the main reason is for mujoco both the policy update computation and simulator step are fast, so overhead related to interprocess communication (when one runs multiple envs in subprocesses) is significant. For atari, on the other hand, policy update computation is relatively slow, so it makes much more sense to run multiple environments while the GPU is crunching the update. 
To @kirk86 's point, for Mujoco we usually use fully-connected policies (because observations are not visual), so GPU's don't actually give that much speed gain over computing updates on CPU. 
We'll be releasing the update to the ppo2 that can run both using MPI and multiple envs in subprocesses for either atari and mujoco (in fact, it is in PR stage https://github.com/openai/baselines/pull/490 , so feel free to give it a spin)
2. The default parameters for mujoco are the ones that work ok, but are not extensively optimized; I don't think anyone has run experiments to properly compare annealed vs constant values for clip_range or learning rate on mujoco to figure out which one is better (@olegklimov, @joschu correct me if I am wrong)... so we use the Occam's razor and choose the simpler :)

**Comment by kirk86** [comment]
@pzhokhov thank you for your answer, it clarifies a lot of things for me! I've also started cleaning up the baselines pretty much same stuff as you mentioned in your PR comments minus the unit testing. I'm happy to contribute back anything you might feel is helpful, just give me a shout. 

BTW @pzhokhov do you have any insight on why does ddpg brake whenever I try to use MPI with more than 2 processes? Eventually I tracked down the error at the variable thetalocal inside mpi_adam.py which becomes a list of NaNs every time the number of processes is bigger than 2. Haven't figured out yet why is this happening?

Also is there any fundamental difference between ddpg and ddpg inside her?

Many thanks!

**Comment by pzhokhov** [comment]
@matthiasplappert could you help out with this one? ^^^

**Comment by matthiasplappert** [comment]
It's hard to debug MPI because there are so many different versions out there. It used to work but I haven't touched this code in a while.

The DDPG implementation for HER is tuned towards that use case and is pretty heavily tied to mujoco.
