### ISSUE TITLE
Normalize state values?

### ISSUE THREAD

**Issue by yoojinoh** [openai/baselines#530]
Hi!
I am trying to train a openai gym environment using baselines. In any case using mlp to train the network, should I rescale (as in shifting my range) my observation values(input data) either from 0 to 1 or from -1 to 1?
It looks like in the train_cartpole example for DQN they don't normalize them.

**Comment by pzhokhov** [comment]
Hi @yoojinoh! The 0..1 vs -1..1 should not matter, because first layer of mlp should be able to learn the correct transformation of inputs (unless you explicitly tell it not to use bias, in which case 0..1 and -1..1 are not equivalent). That being said, if the range is very different from 0..1 (say, 0..255, like in atari games), a normalization is needed.  Also (mainly mentioning it for completeness of the picture), there is an auto-normalizing wrapper class (common.vec_env.vec_normalize.VecNormalize) which keeps track of running mean and standard deviation of observations; but it is a bit tricky to serialize (save/load) models with it. Hope this helps and closing this  - feel free to reopen if it does not quite answer your question.

**Comment by stefanbschneider** [comment]
Is it possible to do the running mean normalization of observations with one of the `gym` wrappers instead?
