### ISSUE TITLE
what's the difference between the same game with different version : v0,...,v4

### ISSUE THREAD

**Issue by initial-h** [openai/baselines#552]
i find there are many versions of the same atari game,like PongNoFrameskip-v4 and so on.

what's the defference and where i can find the introduction?

**Comment by pzhokhov** [comment]
Very good question, had it myself more than once :) @christopherhesse @gdb @joschu who'd be the best person to route this to?

**Comment by christopherhesse** [comment]
I don't know the answer to this, but there are some notes in the gym changelog for a couple of the v* suffixes: https://github.com/openai/gym#whats-new

**Comment by gdb** [comment]
We bump the version whenever there is a semantic change to the environment, no matter how slight. That means you can always trust that `PongNoFrameskip-v3` has *exactly* the same semantics as the version used by some paper. That being said, you should consider all older versions to be deprecated and just use the most recent one — that is, you should think of older versions like a history that is accessible but not intended for normal use. Accordingly, we don't always document the difference between the versions, as you should always be using the most recent one.

**Comment by KristianHolsheimer** [comment]
For Pong there's a nice video that makes the difference immediately clear: https://www.youtube.com/watch?v=zp72VTr730s

**Comment by rfali** [comment]
**Breakout-v0 vs Breakout-v4** 
v0: repeat_action_probability of 0.25 (meaning 25% of the time the previous action will be used instead of the new action)
v4: repeat_action_probability of 0 (always follow issued action)

**Breakout-v4 vs BreakoutDeterministic-v4 vs BreakoutNoFrameskip-v4**
game-vX: frameskip is sampled from (2,5), meaning either 2, 3 or 4 frames are skipped [low: inclusive, high: exclusive]
game-Deterministic-vX: a fixed frame skip of 4
game-NoFrameskip-vX:  with no frame skip

**Breakout-v4 vs Breakout-ram-v4** 
game-vX: Observation Space (128,). Observation is given as a vector of size 128.
game-ram-vX: Observation Space (210,160,3). Observation is given as pixels of Width:210, Height:160, Depth:3

The atari environment source code has been removed from Gym [AFAIK] and you can see it on the ALE's GitHub. See source code [here](https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/gym/envs/atari/environment.py)

Other useful references: 
This [video](https://www.youtube.com/watch?v=WnSUQdFnKyY)
This [GitHub Issue](https://github.com/openai/gym/issues/1280)
ALE v0.7 [Blog](https://brosa.ca/blog/ale-release-v0.7)
