### ISSUE TITLE
SubProcEnv and TRPO issues in traj_segment_generator

### ISSUE THREAD

**Issue by SBuercklin** [openai/baselines#575]
I have an environment which TRPO handles perfectly well if I feed in an individual environment. However, if I instead construct a SubProcEnv with multiple instances of this environment, I run into issues in the trajectory segment generator.

    Traceback (most recent call last):
    File "path/to/file/rl_vector_v0.py", line 119, in <module>
        main()

    File "path/to/file/rl_vector_v0.py", line 89, in main
        num_layers = nl, num_hidden = nhl, activation = tf.nn.leaky_relu

    File "path/to/file/trpo_mpi.py", line 286, in learn
        seg = seg_gen.__next__()

    File "path/to/file/trpo_mpi.py", line 55, in traj_segment_generator
        vpreds[i] = vpred

    ValueError: setting an array element with a sequence.

It appears that the trajectory segment generator is not equipped to deal with the vectorized outputs of the vectorized environment.

My script to run TRPO can be distilled to the following:

    ########################################
    # Set up the computational environment
    ########################################
    sess = U.make_session()
    sess.__enter__()
    # Set environment paramdict
    
    def make_env():
        env = gym.make("MyEnv-v0")
        return env

    ########################################
    # Run TRPO
    ########################################
    vector_env = subproc_vec_env.SubprocVecEnv([make_env, make_env, make_env])

    pol_net = build_policy(vector_env, 'mlp', num_layers = nl, num_hidden = nhl, 
            activation = tf.nn.leaky_relu)

    eps_per_batch = 15
    num_iters = 100

    pi = trpo_mpi.learn(network='mlp', env=vector_env, 
        total_timesteps = N*eps_per_batch*num_iters,
        timesteps_per_batch=N*eps_per_batch, 
        num_layers = nl, num_hidden = nhl, activation = tf.nn.leaky_relu
        )

**Comment by pzhokhov** [comment]
Hi @SBuercklin! This particular TRPO implementation was not written to handle vectorized environments. Instead, if you need multiple environments to be simulated in parallel, you can use MPI workers (so that each worker interacts with one environment, but they all share the gradients and parameter updates by using MpiAdamOptimizer. 
To run your script with mpi, you'll need mpi4py package, and use
`mpirun -np <num_workers> your_script.py`
(Also note that if you are seeding environments deterministically, the seeds need to be different on different workers)
It is likely possible to make TRPO work with vecenvs as well, but I'd recommend using MPI and do not have a timeline for when TRPO-vecenv compatibility.
