### ISSUE TITLE
Return True before conditional check in _check_shape (common/tf_util.py)

### ISSUE THREAD

**Issue by ssmint** [openai/baselines#580]
Was the function intentionally return True?

https://github.com/openai/baselines/blob/23b2333238e9850a230f0fa3ce95497d4c6c418b/baselines/common/tf_util.py#L394

**Comment by pzhokhov** [comment]
no, but turns out that current implementation of _check_shape returns False sometimes when it should return True. On the other hand, if it incorrectly returns True, most likely there would be a failure downstream anyways; that's why it was not high on a priority list to fix that. See discussion here: 
https://github.com/openai/baselines/pull/571

**Comment by ssmint** [comment]
Thanks! I will close the issue then.
