### ISSUE TITLE
About the reward on A2C & ACKTR

### ISSUE THREAD

**Issue by Nara0731** [openai/baselines#606]
Hi,
When I run the PPO, it can show the ep_reward as "eprewmean ". However, when I run the A2C or ACKTR, it shows nothing about the reward.

**Comment by simoninithomas** [comment]
Hi @Nara0731,

Episode reward mean depends on the environment, because this element is taken from info, I remember that when I used it with openai retro the output was nan (because with Sonic there is no this element in info). So I think it works only with openai gym environments but I'm not 100% sure.

What you can do with A2C is **adding a testing loop for each 5 epochs for instance, that way you'll see if your agent performs better.**

**Comment by fuxianh** [comment]
@Nara0731 Hi, bro. Have you got any way to get the reward of A2C or ACKTR?

**Comment by slerman12** [comment]
I'm struggling with this too. Need to report reward over time statistics for my experiments.
