### ISSUE TITLE
What is the version of mujoco and gym that is required to run a baseline code?

### ISSUE THREAD

**Issue by NishanthVAnand** [openai/baselines#625]
I currently have `gym==0.9.3` and mujoco version at `mujoco-py==0.5.7`. I get error when I run the PPO code. Below is the error I get
`from gym.wrappers import FlattenDictWrapper
ImportError: cannot import name 'FlattenDictWrapper'`

**Comment by pzhokhov** [comment]
Hi @NishanthVAnand! Thanks for pointing it out, we'll constrain the version of gym required by baselines. You'll need gym >= 0.10, and mujoco>=1.50 (I'd recommend installing the latest if you don't have a particular attachment to the old version)
 `pip install gym[mujoco] --update` would pull latest gym and a correct version of mujoco with it.

**Comment by Derekabc** [comment]
does `pip install gym[mujoco] --update` mean `pip install gym[0.5.7] --update`, it fails.

**Comment by Muguangfeng** [comment]
Hi! Have you solved the problem? I made the similar mistake with you. I have update to gym0.12 and mujoco1.50, mujoco-py1.50.1.68, but it is still the problem.

**Comment by Derekabc** [comment]
@Muguangfeng I solved the problem, maybe you can have a try: `https://github.com/openai/mujoco-py/issues/244`

**Comment by Muguangfeng** [comment]
As you said: Using low version of gym, may cause prolem like: ImportError cannot import name FlattenDictWrapper
I have tried gym0.10.5、gym0.12 with mujoco131 or mujoco150, but it is still this problem. Shouldn't this error only be related to gym? 
Do I still need to try mujoco 200? This is not what I want，because mujoco200 may require a different license with mujoco131 and mujoco150.

**Comment by Derekabc** [comment]
I think it is related to the version of gym. I faced the problem and then I
only updated the gym, it works. It seems you can use the same license for
different version of mujoco. just make a copy and have a try.

Muguangfeng <notifications@github.com> 于2019年4月26日周五 上午10:42写道：

**Comment by Muguangfeng** [comment]
Thanks，I will have a try.

**Comment by pzhokhov** [comment]
So that particular error, `ImportError: cannot import name 'FlattenDictWrapper'` on `from gym.wrappers import FlattenDictWrapper` occurs in the gym versions < 0.10.0. Any gym version >= 0.10.0 should work, including gym installed from master branch

**Comment by pzhokhov** [comment]
Gym version required for baselines is now contrained (https://github.com/openai/baselines/pull/885). Closing this issue.

**Comment by Muguangfeng** [comment]
Hi! I installed gym0.10.5 by running pip install gym==0.10.5, but it is still the problem:ImportError cannot import name FlattenDictWrapper.
Does I need to run pip install gym[all].
If i do like this, it tell me that i need install mujoco200. I don't want to install mujoco200, because my another code requests mujoco131. Is there any solutions.

**Comment by Derekabc** [comment]
So,I think you can install both of them. Just modify the path  on your bashrc file before you decide which one you want to use.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
