### ISSUE TITLE
How to access the "info" that is generated during each env.step()

### ISSUE THREAD

**Issue by cli0** [openai/baselines#658]
I have programmed my environment to provide some additional information in the info field and now I am training my agent using deepq. However, I don't see how to make my environment print the content of info in addition to the digest that I get (time spent exploring, mean average etc.) My code is like this:

```
env = Monitor(env, log_dir, allow_early_resets=True)

act = deepq.learn(
    env=env,
    network="mlp",
    total_timesteps=200000,
    gamma=0.8,
    prioritized_replay= True
)
```

Is there a way to log environment info in the monitor.csv file?

**Comment by pzhokhov** [comment]
Hi @cli0! Current implementation of deepq does not make use of info dict that is generated by env.step() - it is discaded, specifically here: https://github.com/openai/baselines/blob/fc7f9cec49786d50bb635228da0062972bdcf967/baselines/deepq/deepq.py#L284

f you want that info to be saved into monitor.csv, you can modify the code in baselines/bench/monitor.py (note that each line in that file corresponds to a complete episode rather than a single step). If you want the data to be printed to the screen into the summary, you can modify the deepq code (the line above and section around logging https://github.com/openai/baselines/blob/fc7f9cec49786d50bb635228da0062972bdcf967/baselines/deepq/deepq.py#L314) to add your stats of interest to the logger (this way, stats can be printed out, saved as a csv and in tensorboard format). 
The difference in how various algos interact with info dict is indeed a bit annoying; and unifying it is a good idea, but it is not very high up on our todo list. 
Hope this helps and closing it, feel free to reopen if something does not work out.
