### ISSUE TITLE
Update PyPi package

### ISSUE THREAD

**Issue by pvarin** [openai/baselines#693]
I'd like to be able to run the baselines code by importing baselines and calling the `run` module function directly like so:
```
import gym_foo # registers my custom environments
from baselines.run import main

main()
```
This works fine when I clone baselines and use `pip install -e .` but not when I install the repository from PyPi because the current package version on PyPi predates the `baselines/run.py` file.

**Comment by pzhokhov** [comment]
The pypi package is not maintained at the moment - partially due to number of recent backwards-incompatible changes, partially because we see baselines more as a starter for research and a collection of components that may need to be modified to suit one's needs than an immutable software library. 
We may come back to maintaining the pypi package in the future; for now  if a one-liner installation is needed, I'd recommend `pip install git+https://github.com/openai/baselines` for the latest version, and `pip install git+https://github.com/openai/baselines.git@<commit_hash>` if a particular commit is needed.

**Comment by motiwari** [comment]
@pzhokhov thanks for your response above. Request: could you remove it from pypi altogether? I tried installing `baselines` for another project using `pip install baselines`, and didn't realize I had such an outdated version that was causing errors.

**Comment by pzhokhov** [comment]
let me see what I can do about that
