### ISSUE TITLE
Incomplete policy loss gradient in PPO2

### ISSUE THREAD

**Issue by ojasjoshi** [openai/baselines#708]
Policy loss calculation uses an action placeholder for the sampled action from a gaussian normal pd. So the gradient does not go through the sampled action although the sample is coming from a pd with current mean and std params (both trainable param outputs). Not sure what is the scale of this blocked gradient but doesn't ignoring this gradient make the gradient calculation incomplete? Is their an alternative way to sample actions without using reparameterization to make this gradient calculation possible?

**Comment by pzhokhov** [comment]
I think propagating gradient through action would lead to a completely wrong result. Consider this:
the policy gradient is written in the form 
<a href="https://www.codecogs.com/eqnedit.php?latex=\sum_i&space;A_i&space;\nabla_\theta&space;\log&space;\pi_\theta(a_i&space;|&space;s_i)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\sum_i&space;A_i&space;\nabla_\theta&space;\log&space;\pi_\theta(a_i&space;|&space;s_i)" title="\sum_i A_i \nabla_\theta \log \pi_\theta(a_i | s_i)" /></a>
(where sum_i stands for some over trajectory (or trajectories in the batch), and A_i is an estimate of advantage of some sort). Your argument is that a_i depends on theta, so should also be differentiated. 
Imagine policy is gaussian, and has standard deviation of 1 for simplicity:

<a href="https://www.codecogs.com/eqnedit.php?latex=\pi_\theta(a_i&space;|&space;s_i)&space;=&space;\frac{1}{\sqrt{2\pi}}&space;e^{-(a_i&space;-&space;\mu_\theta(s_i))^2}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\pi(a_i&space;|&space;s_i)&space;=&space;\frac{1}{\sqrt{2\pi}}&space;e^{-(a_i&space;-&space;\mu(s_i))^2}" title="\pi_\theta(a_i | s_i) = \frac{1}{\sqrt{2\pi}} e^{-(a_i - \mu(s_i))^2}" /></a>
Here mu_theta(s_i) is the output of the neural net, parameterized by theta. Then
<a href="https://www.codecogs.com/eqnedit.php?latex=\log&space;\pi_\theta(a_i&space;|&space;s_i)&space;=&space;-(a_i&space;-&space;\mu_\theta(s_i))^2&space;-&space;\frac{1}{2}\log(2\pi)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\log&space;\pi_\theta(a_i&space;|&space;s_i)&space;=&space;-(a_i&space;-&space;\mu_\theta(s_i))^2&space;-&space;\frac{1}{2}\log(2\pi)" title="\log \pi_\theta(a_i | s_i) = -(a_i - \mu_\theta(s_i))^2 - \frac{1}{2}\log(2\pi)" /></a>
If we differentiate expression above wrt to theta while keeping a_i constant, it produces some gradient. However, if we consider a_i function of theta: 
<a href="https://www.codecogs.com/eqnedit.php?latex=a_i&space;=&space;\mu_\theta(s_i)&space;&plus;&space;\xi" target="_blank"><img src="https://latex.codecogs.com/gif.latex?a_i&space;=&space;\mu_\theta(s_i)&space;&plus;&space;\xi" title="a_i = \mu_\theta(s_i) + \xi" /></a>
where xi is a random variable ~ N(0,1). Therefore, 

<a href="https://www.codecogs.com/eqnedit.php?latex=\log&space;\pi_\theta(a_i&space;|&space;s_i)&space;=&space;-\xi^2&space;-&space;\frac{1}{2}\log(2\pi)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\log&space;\pi_\theta(a_i&space;|&space;s_i)&space;=&space;-\xi^2&space;-&space;\frac{1}{2}\log(2\pi)" title="\log \pi_\theta(a_i | s_i) = -\xi^2 - \frac{1}{2}\log(2\pi)" /></a> 
so
<a href="https://www.codecogs.com/eqnedit.php?latex=\nabla_\theta&space;\log&space;\pi_\theta(a_i&space;|&space;s_i)&space;=&space;0" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\nabla_\theta&space;\log&space;\pi_\theta(a_i&space;|&space;s_i)&space;=&space;0" title="\nabla_\theta \log \pi_\theta(a_i | s_i) = 0" /></a>
because all theta dependency cancelled out.
