### ISSUE TITLE
run baseline with mpi -np 1, performance decrease dramatically

### ISSUE THREAD

**Issue by scotthuang1989** [openai/baselines#753]
This is how I measure the time spend on interacting with environment:

in ppo.py , function: learn

 **data_collecting_time = deque(maxlen=1000)
       t_start = time.time()**
        obs, returns, masks, actions, values, neglogpacs, states, epinfos = runner.run()
        **data_collecting_time.append(time.time() - t_start)**

**print("mean data collecting time: ", sum(data_collecting_time)/len(data_collecting_time))**

**code marked with bold is my code.**

if I run with following command:

`python -m baselines.run_stock  xxxx`

it will take 10 seconds.

if I run with this command:
`mpirun -np 1 python -m baselines.run_stock  xxxx`

it will take 30 seconds.

I don't understand this. because I think these 2 command should have same effect. Can someone help me?

**Comment by pzhokhov** [comment]
Interesting... There is no MPI calls in runner.run() methods, so they should indeed give the same result.  That being said, I tried this experiment on mujoco ant and did not see similar behaviour. I used your code measuring specifically how long do the rollouts take, it was ~ 2 +- 0.03 s both with and without MPI. I also tried it with --num_env=2 (so that subprocess-based parallel rollouts can be tested) - also same result. Thus, I suspect it is something specific to your environment... Are there any MPI calls in your environment? Could you provide some details on what it is?

**Comment by scotthuang1989** [comment]
yes. I save log only on rank 0. but it should cause this. I will check my code and run the experiment again when I have resources, because I should run this on a  machine with almost zero loading to rule out potential impact of other factor.
Actually, I have used this new baseline for 2 weeks, I have observed that both rollout and train time is extremely unstable, I am trying to figure it out why.  

Do you have benchmark data for your **MpiAdamOptimizer**? if I substitute it with [horovod](https://github.com/uber/horovod), the training time will be more stable and faster on average. I think the idea of MpiAdamOptimizer and horovod is same, just some implementation differences.
