### ISSUE TITLE
Intuition behind batch sizes

### ISSUE THREAD

**Issue by Olimoyo** [openai/baselines#755]
Does anyone have a good intuition or explanation behind the choice of batch size for different algorithms? 

I noticed that for TRPO/PPO the batch size is usually set as ~2048 by default, but on the other hand for A2C the default batch size tends to be closer to ~80. 

Does it have to do with discrete control vs continuous control? In this paper (https://arxiv.org/pdf/1708.05144.pdf), they use the following batch sizes:
Discrete
ACKTR: 640
A2C: 80
TRPO: 512

Continuous
ACKTR: 2500
A2C: 2500
TRPO: 25000

**Comment by pzhokhov** [comment]
From what I understand, optimal batch size for deep learning is a subject of active research (see for instance https://arxiv.org/pdf/1812.06162.pdf and references therein). Now, since you asked about intuition, mine is that the bigger the batch size, the better are gradient estimates, so bigger batches are better... Discrete vs continuous control enters this somewhat tangentially - in typical discrete control problems, like atari, the observation spaces are images. Running multi-layer convolutional nets on images requires much more memory (GPU RAM)  than fully connected nets with small observation spaces in case of continuous control problems, and that limits the batch size.  Hope this helps! Also, I'd suggest not taking my intuition too seriously, and for problem of interest actually run experiments with several batch sizes.

**Comment by Olimoyo** [comment]
Thanks! That actually helps a lot.
