### ISSUE TITLE
eplenmean and eprewmean always nan

### ISSUE THREAD

**Issue by mitar** [openai/baselines#762]
For my own environment, when I run ppo2, I am always getting `nan` for `eplenmean` and `eprewmean`. I see from the code that it uses `'l'` and `'r'` keys from debug info returned from step calls. But what are those values? Where it is documented?

**Comment by araffin** [comment]
Related: https://github.com/hill-a/stable-baselines/issues/24

**Comment by mitar** [comment]
Oh, it seems I just have to wrap my env with `Monitor` wrapper. I can even make file `None` to not log it, just populate those fields. Cool.

Is this documented anywhere?

**Comment by DanielTakeshi** [comment]
In general most of the gym or env stuff isn't documented beyond what you might see here:

https://gym.openai.com/docs/

It's a lot of trial and error but the code itself isn't too bad to read (it does take some time, though).

**Comment by tkelestemur** [comment]
@mitar How 'Monitor' helps to fix this? I'm having the same problem with my custom environment. I only wrapped with `TimeLimit` so that the episode will end when it reaches the `max_number_steps`.

**Comment by pzhokhov** [comment]
@tkelestemur Monitor wrapper reports lengths and rewards of each episode in the info dict (fourth return value from env.step); the reason why it helps to fix the nan problem with ppo2 is because ppo2 uses those values for reporting - if there are none, ppo2 will report NaN's. 
In your case, however, the environment seemed to be created correctly... looking at your code here (https://github.com/tkelestemur/sawyer_gym/blob/master/train_baseline.py) (I suspect that's what you are referring to) - I think there is a wrong Monitor imported. I.e. if you replace `from gym.wrappers import Monitor` to `from baselines.bench import Monitor` ppo2 will report things correctly (or at least seemingly correclty, I did not look very deeply in the values). 
Now, you may say "wtf this is so confusing", and I will agree with that :) Will look into why the one in gym does not work correctly with ppo2.

**Comment by pzhokhov** [comment]
oh I see the one in gym does something completely different - it tries to record a video of agent interacting with the environment. Ugh. This is an unfortunate name collision. We'll fix it one way or another; in the mean time, I'll close this - don't see any actionable here (other than improving the docs - which there is already plenty of open issues about).

**Comment by tkelestemur** [comment]
@pzhokhov Thanks a lot for going over my environment. I tried the `Monitor` from `baselines.bench` and it worked perfectly fine. In fact, the performance is really good. When I was looking at the `https://github.com/openai/baselines/blob/master/baselines/run.py` to see how I can use PPO without a registered Gym environment, I skipped the `Monitor` because I thought it was doing what Gym's `Monitor` does which is recording videos of the agent. 

Thanks for the help!
