### ISSUE TITLE
observation normalization?

### ISSUE THREAD

**Issue by hankly** [openai/baselines#802]
https://github.com/openai/baselines/blob/b55eda1dde7292a56ad63d8a849198100bd26a17/baselines/gail/adversary.py#L69

In gail/adeversay.py Line 69.
I suppose it normalize obs.but ,is it something wrong?
 
it should be `obs = (obs_ph - self.obs_rms.mean) / self.obs_rms.std` instead?

**Comment by mingfeisun** [comment]
https://github.com/openai/baselines/blob/5b41c926c7a852df3f0928afdf2429f96a3965cb/baselines/gail/adversary.py#L69
This line is inconsistent with:
https://github.com/openai/baselines/blob/5b41c926c7a852df3f0928afdf2429f96a3965cb/baselines/gail/mlp_policy.py#L36
So that line in **Adversary.py** should be:
`obs = (obs_ph - self.obs_rms.mean) / self.obs_rms.std`
And it makes more sense.

**Comment by pzhokhov** [comment]
fixed in https://github.com/openai/baselines/pull/823
