### ISSUE TITLE
Is the PPO2 optimization synchronous or asynchronous between the different agents ?

### ISSUE THREAD

**Issue by Deathn0t** [openai/baselines#993]
Hi,

about the optimization strategy for PPO2, do you know if Is the optimization process is synchronous or asynchronous between the different agents?

Thank you for your help.

**Comment by pisiiki** [comment]
PPO is on-policy. The network updates are synchronous, however not all the env.'s may have been used. The ppo2 implementation collects samples until it can fill a minibatch. The order of filling is determined beforehand by doing random slices of the env. index list. When all the env.'s have been used a new index list is generated.

All the samples are generated with the most updated network, no network copies are used. No env. steps are taken while updating the network.

For the sequential (ie: lstm) case this means that you need to fill a fixed number of steps per env. per minibatch. This requires the minibatch size to be divisible by the bptt length. The algorithm will alternate groups of env.'s and fill the minibatch acordingly. The sequential code is much more involved since you also need to keep track of the lstm states.

I hope this is accurate with the current code since I haven't checked it in a while.

I recommend you to step the code with a debugger in both (sequential and nonsequential) cases.

Regards.

**Comment by christopherhesse** [comment]
Thanks for ansering @pisiiki !
